package com.podbelly.core.common.theme.catalog

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.podbelly.core.common.AppTheme
import com.podbelly.core.common.theme.ThemeCategory
import com.podbelly.core.common.theme.ThemeSpec

object DeveloperThemes {

    private val dracula = darkColorScheme(
        primary = Color(0xFFBD93F9),
        onPrimary = Color(0xFF21222C),
        primaryContainer = Color(0xFF44396B),
        onPrimaryContainer = Color(0xFFE4D6FF),
        secondary = Color(0xFFFF79C6),
        onSecondary = Color(0xFF21222C),
        secondaryContainer = Color(0xFF6B2E52),
        onSecondaryContainer = Color(0xFFFFD1EC),
        tertiary = Color(0xFF8BE9FD),
        onTertiary = Color(0xFF21222C),
        tertiaryContainer = Color(0xFF1E4A54),
        onTertiaryContainer = Color(0xFFC2F5FF),
        error = Color(0xFFFF5555),
        onError = Color(0xFF21222C),
        errorContainer = Color(0xFF6B1F1F),
        onErrorContainer = Color(0xFFFFC2C2),
        background = Color(0xFF282A36),
        onBackground = Color(0xFFF8F8F2),
        surface = Color(0xFF282A36),
        onSurface = Color(0xFFF8F8F2),
        surfaceVariant = Color(0xFF44475A),
        onSurfaceVariant = Color(0xFFC7C9D9),
        outline = Color(0xFF6272A4),
        outlineVariant = Color(0xFF44475A),
    )

    private val nord = darkColorScheme(
        primary = Color(0xFF88C0D0),
        onPrimary = Color(0xFF2E3440),
        primaryContainer = Color(0xFF2E4A54),
        onPrimaryContainer = Color(0xFFD6EAF0),
        secondary = Color(0xFF81A1C1),
        onSecondary = Color(0xFF2E3440),
        secondaryContainer = Color(0xFF2F3E52),
        onSecondaryContainer = Color(0xFFD5E0EC),
        tertiary = Color(0xFFA3BE8C),
        onTertiary = Color(0xFF2E3440),
        tertiaryContainer = Color(0xFF3A4A32),
        onTertiaryContainer = Color(0xFFE0EAD4),
        error = Color(0xFFBF616A),
        onError = Color(0xFF2E3440),
        errorContainer = Color(0xFF5A2A30),
        onErrorContainer = Color(0xFFF3D2D6),
        background = Color(0xFF2E3440),
        onBackground = Color(0xFFECEFF4),
        surface = Color(0xFF3B4252),
        onSurface = Color(0xFFECEFF4),
        surfaceVariant = Color(0xFF434C5E),
        onSurfaceVariant = Color(0xFFD8DEE9),
        outline = Color(0xFF4C566A),
        outlineVariant = Color(0xFF434C5E),
    )

    private val gruvbox = darkColorScheme(
        primary = Color(0xFFFE8019),
        onPrimary = Color(0xFF282828),
        primaryContainer = Color(0xFF6B3410),
        onPrimaryContainer = Color(0xFFFFD9B8),
        secondary = Color(0xFF8EC07C),
        onSecondary = Color(0xFF282828),
        secondaryContainer = Color(0xFF3A4A32),
        onSecondaryContainer = Color(0xFFD8EACB),
        tertiary = Color(0xFFFABD2F),
        onTertiary = Color(0xFF282828),
        tertiaryContainer = Color(0xFF5C4A12),
        onTertiaryContainer = Color(0xFFFBEBB5),
        error = Color(0xFFFB4934),
        onError = Color(0xFF282828),
        errorContainer = Color(0xFF5C1E17),
        onErrorContainer = Color(0xFFFCD2CC),
        background = Color(0xFF282828),
        onBackground = Color(0xFFEBDBB2),
        surface = Color(0xFF32302F),
        onSurface = Color(0xFFEBDBB2),
        surfaceVariant = Color(0xFF3C3836),
        onSurfaceVariant = Color(0xFFBDAE93),
        outline = Color(0xFF665C54),
        outlineVariant = Color(0xFF3C3836),
    )

    private val solarizedDark = darkColorScheme(
        primary = Color(0xFF268BD2),
        onPrimary = Color(0xFF002B36),
        primaryContainer = Color(0xFF0E3A52),
        onPrimaryContainer = Color(0xFFC4E1F2),
        secondary = Color(0xFF2AA198),
        onSecondary = Color(0xFF002B36),
        secondaryContainer = Color(0xFF0D3F3B),
        onSecondaryContainer = Color(0xFFC2ECE8),
        tertiary = Color(0xFF859900),
        onTertiary = Color(0xFF002B36),
        tertiaryContainer = Color(0xFF3A4200),
        onTertiaryContainer = Color(0xFFE4EBB8),
        error = Color(0xFFDC322F),
        onError = Color(0xFF002B36),
        errorContainer = Color(0xFF5C1513),
        onErrorContainer = Color(0xFFF5CBCA),
        background = Color(0xFF002B36),
        onBackground = Color(0xFF839496),
        surface = Color(0xFF073642),
        onSurface = Color(0xFF839496),
        surfaceVariant = Color(0xFF094350),
        onSurfaceVariant = Color(0xFF93A1A1),
        outline = Color(0xFF586E75),
        outlineVariant = Color(0xFF094350),
    )

    private val solarizedLight = lightColorScheme(
        primary = Color(0xFF268BD2),
        onPrimary = Color(0xFFFDF6E3),
        primaryContainer = Color(0xFFCBE3F2),
        onPrimaryContainer = Color(0xFF0E3A52),
        secondary = Color(0xFF2AA198),
        onSecondary = Color(0xFFFDF6E3),
        secondaryContainer = Color(0xFFC8ECE8),
        onSecondaryContainer = Color(0xFF0D3F3B),
        tertiary = Color(0xFF859900),
        onTertiary = Color(0xFFFDF6E3),
        tertiaryContainer = Color(0xFFE4EBB8),
        onTertiaryContainer = Color(0xFF3A4200),
        error = Color(0xFFDC322F),
        onError = Color(0xFFFDF6E3),
        errorContainer = Color(0xFFF5CBCA),
        onErrorContainer = Color(0xFF5C1513),
        background = Color(0xFFFDF6E3),
        onBackground = Color(0xFF586E75),
        surface = Color(0xFFEEE8D5),
        onSurface = Color(0xFF657B83),
        surfaceVariant = Color(0xFFE3DCC8),
        onSurfaceVariant = Color(0xFF586E75),
        outline = Color(0xFF93A1A1),
        outlineVariant = Color(0xFFE3DCC8),
    )

    private val monokai = darkColorScheme(
        primary = Color(0xFFF92672),
        onPrimary = Color(0xFF272822),
        primaryContainer = Color(0xFF6B1030),
        onPrimaryContainer = Color(0xFFFCC7D9),
        secondary = Color(0xFFA6E22E),
        onSecondary = Color(0xFF272822),
        secondaryContainer = Color(0xFF44531A),
        onSecondaryContainer = Color(0xFFE4F5C2),
        tertiary = Color(0xFF66D9EF),
        onTertiary = Color(0xFF272822),
        tertiaryContainer = Color(0xFF1C4C56),
        onTertiaryContainer = Color(0xFFC6F1F9),
        error = Color(0xFFF92672),
        onError = Color(0xFF272822),
        errorContainer = Color(0xFF6B1030),
        onErrorContainer = Color(0xFFFCC7D9),
        background = Color(0xFF272822),
        onBackground = Color(0xFFF8F8F2),
        surface = Color(0xFF2D2E27),
        onSurface = Color(0xFFF8F8F2),
        surfaceVariant = Color(0xFF3E3D32),
        onSurfaceVariant = Color(0xFFCFCFC2),
        outline = Color(0xFF75715E),
        outlineVariant = Color(0xFF3E3D32),
    )

    private val tokyoNight = darkColorScheme(
        primary = Color(0xFF7AA2F7),
        onPrimary = Color(0xFF1A1B26),
        primaryContainer = Color(0xFF2A3A5E),
        onPrimaryContainer = Color(0xFFD3DFFA),
        secondary = Color(0xFFBB9AF7),
        onSecondary = Color(0xFF1A1B26),
        secondaryContainer = Color(0xFF3E2F5E),
        onSecondaryContainer = Color(0xFFE6DAFA),
        tertiary = Color(0xFF7DCFFF),
        onTertiary = Color(0xFF1A1B26),
        tertiaryContainer = Color(0xFF1F4A5E),
        onTertiaryContainer = Color(0xFFD0EEFC),
        error = Color(0xFFF7768E),
        onError = Color(0xFF1A1B26),
        errorContainer = Color(0xFF5E202C),
        onErrorContainer = Color(0xFFFAD3DA),
        background = Color(0xFF1A1B26),
        onBackground = Color(0xFFC0CAF5),
        surface = Color(0xFF24283B),
        onSurface = Color(0xFFC0CAF5),
        surfaceVariant = Color(0xFF2F334D),
        onSurfaceVariant = Color(0xFF9AA5CE),
        outline = Color(0xFF565F89),
        outlineVariant = Color(0xFF2F334D),
    )

    val specs: List<ThemeSpec> = listOf(
        ThemeSpec(AppTheme.DRACULA, "Dracula", ThemeCategory.DEVELOPER, dracula),
        ThemeSpec(AppTheme.NORD, "Nord", ThemeCategory.DEVELOPER, nord),
        ThemeSpec(AppTheme.GRUVBOX, "Gruvbox", ThemeCategory.DEVELOPER, gruvbox),
        ThemeSpec(AppTheme.SOLARIZED_DARK, "Solarized Dark", ThemeCategory.DEVELOPER, solarizedDark),
        ThemeSpec(AppTheme.SOLARIZED_LIGHT, "Solarized Light", ThemeCategory.DEVELOPER, solarizedLight),
        ThemeSpec(AppTheme.MONOKAI, "Monokai", ThemeCategory.DEVELOPER, monokai),
        ThemeSpec(AppTheme.TOKYO_NIGHT, "Tokyo Night", ThemeCategory.DEVELOPER, tokyoNight),
    )
}
