package com.podbelly.core.common.theme.catalog

import androidx.compose.material3.darkColorScheme
import androidx.compose.ui.graphics.Color
import com.podbelly.core.common.AppTheme
import com.podbelly.core.common.theme.ThemeCategory
import com.podbelly.core.common.theme.ThemeSpec

object RetroComputingThemes {

    private val commodore64Scheme = darkColorScheme(
        primary = Color(0xFFA599E9),
        onPrimary = Color(0xFF211862),
        primaryContainer = Color(0xFF352A8C),
        onPrimaryContainer = Color(0xFFCDC5FF),
        secondary = Color(0xFF8B7EE0),
        onSecondary = Color(0xFF211862),
        secondaryContainer = Color(0xFF3B2F96),
        onSecondaryContainer = Color(0xFFCDC5FF),
        tertiary = Color(0xFFB5AAF0),
        onTertiary = Color(0xFF211862),
        tertiaryContainer = Color(0xFF3B2F96),
        onTertiaryContainer = Color(0xFFCDC5FF),
        background = Color(0xFF40318D),
        onBackground = Color(0xFFB5AAF0),
        surface = Color(0xFF483BA0),
        onSurface = Color(0xFFB5AAF0),
        surfaceVariant = Color(0xFF524495),
        onSurfaceVariant = Color(0xFFB5AAF0),
        outline = Color(0xFF8B7EE0),
        outlineVariant = Color(0xFF524495),
    )

    private val terminalGreenScheme = darkColorScheme(
        primary = Color(0xFF00FF41),
        onPrimary = Color(0xFF001A00),
        primaryContainer = Color(0xFF003D14),
        onPrimaryContainer = Color(0xFF7CFFA0),
        secondary = Color(0xFF00CC33),
        onSecondary = Color(0xFF001A00),
        secondaryContainer = Color(0xFF00330D),
        onSecondaryContainer = Color(0xFF7CFFA0),
        tertiary = Color(0xFF33FF66),
        onTertiary = Color(0xFF001A00),
        tertiaryContainer = Color(0xFF003D14),
        onTertiaryContainer = Color(0xFF7CFFA0),
        background = Color(0xFF000D00),
        onBackground = Color(0xFF33FF66),
        surface = Color(0xFF001500),
        onSurface = Color(0xFF33FF66),
        surfaceVariant = Color(0xFF002200),
        onSurfaceVariant = Color(0xFF00CC33),
        outline = Color(0xFF008F26),
        outlineVariant = Color(0xFF002200),
    )

    private val terminalAmberScheme = darkColorScheme(
        primary = Color(0xFFFFB000),
        onPrimary = Color(0xFF1A0F00),
        primaryContainer = Color(0xFF3D2900),
        onPrimaryContainer = Color(0xFFFFD980),
        secondary = Color(0xFFCC8800),
        onSecondary = Color(0xFF1A0F00),
        secondaryContainer = Color(0xFF332100),
        onSecondaryContainer = Color(0xFFFFD980),
        tertiary = Color(0xFFFFC94D),
        onTertiary = Color(0xFF1A0F00),
        tertiaryContainer = Color(0xFF3D2900),
        onTertiaryContainer = Color(0xFFFFD980),
        background = Color(0xFF0D0800),
        onBackground = Color(0xFFFFB000),
        surface = Color(0xFF150E00),
        onSurface = Color(0xFFFFB000),
        surfaceVariant = Color(0xFF221800),
        onSurfaceVariant = Color(0xFFCC8800),
        outline = Color(0xFF8F6200),
        outlineVariant = Color(0xFF221800),
    )

    private val msDosScheme = darkColorScheme(
        primary = Color(0xFF55FFFF),
        onPrimary = Color(0xFF001515),
        primaryContainer = Color(0xFF003838),
        onPrimaryContainer = Color(0xFFAAFFFF),
        secondary = Color(0xFFFF55FF),
        onSecondary = Color(0xFF150015),
        secondaryContainer = Color(0xFF380038),
        onSecondaryContainer = Color(0xFFFFAAFF),
        tertiary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFF2A2A2A),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFF000000),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF0A0A0A),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF1A1A1A),
        onSurfaceVariant = Color(0xFF55FFFF),
        outline = Color(0xFF55FFFF),
        outlineVariant = Color(0xFF1A1A1A),
    )

    private val zxSpectrumScheme = darkColorScheme(
        primary = Color(0xFFD80000),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF3D0000),
        onPrimaryContainer = Color(0xFFFF8080),
        secondary = Color(0xFF00D8D8),
        onSecondary = Color(0xFF001515),
        secondaryContainer = Color(0xFF003838),
        onSecondaryContainer = Color(0xFF80FFFF),
        tertiary = Color(0xFFD8D800),
        onTertiary = Color(0xFF151500),
        tertiaryContainer = Color(0xFF383800),
        onTertiaryContainer = Color(0xFFFFFF80),
        background = Color(0xFF000000),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF0A0A0A),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF1A1A1A),
        onSurfaceVariant = Color(0xFFC0C0C0),
        outline = Color(0xFF00D800),
        outlineVariant = Color(0xFF1A1A1A),
    )

    private val amigaScheme = darkColorScheme(
        primary = Color(0xFFFF8800),
        onPrimary = Color(0xFF1A0E00),
        primaryContainer = Color(0xFF3D2100),
        onPrimaryContainer = Color(0xFFFFCC88),
        secondary = Color(0xFFEDEDED),
        onSecondary = Color(0xFF00243D),
        secondaryContainer = Color(0xFF004178),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFF00243D),
        tertiaryContainer = Color(0xFF004178),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFF0058A8),
        onBackground = Color(0xFFF5F5F5),
        surface = Color(0xFF004E96),
        onSurface = Color(0xFFF5F5F5),
        surfaceVariant = Color(0xFF00619B),
        onSurfaceVariant = Color(0xFFD0E4F5),
        outline = Color(0xFFF5F5F5),
        outlineVariant = Color(0xFF00619B),
    )

    private val appleIIScheme = darkColorScheme(
        primary = Color(0xFF14F074),
        onPrimary = Color(0xFF001A0C),
        primaryContainer = Color(0xFF003D1E),
        onPrimaryContainer = Color(0xFF9CFFC8),
        secondary = Color(0xFFB86BFF),
        onSecondary = Color(0xFF1A0033),
        secondaryContainer = Color(0xFF35145C),
        onSecondaryContainer = Color(0xFFE3C6FF),
        tertiary = Color(0xFFFF7A1A),
        onTertiary = Color(0xFF1A0A00),
        tertiaryContainer = Color(0xFF3D2000),
        onTertiaryContainer = Color(0xFFFFC69C),
        background = Color(0xFF050505),
        onBackground = Color(0xFFE8E8E8),
        surface = Color(0xFF0D0D0D),
        onSurface = Color(0xFFE8E8E8),
        surfaceVariant = Color(0xFF1A1A1A),
        onSurfaceVariant = Color(0xFF4A90FF),
        outline = Color(0xFF4A90FF),
        outlineVariant = Color(0xFF1A1A1A),
    )

    val specs: List<ThemeSpec> = listOf(
        ThemeSpec(AppTheme.COMMODORE_64, "Commodore 64", ThemeCategory.RETRO_COMPUTING, commodore64Scheme),
        ThemeSpec(AppTheme.TERMINAL_GREEN, "Terminal Green", ThemeCategory.RETRO_COMPUTING, terminalGreenScheme),
        ThemeSpec(AppTheme.TERMINAL_AMBER, "Terminal Amber", ThemeCategory.RETRO_COMPUTING, terminalAmberScheme),
        ThemeSpec(AppTheme.MS_DOS, "MS-DOS (CGA)", ThemeCategory.RETRO_COMPUTING, msDosScheme),
        ThemeSpec(AppTheme.ZX_SPECTRUM, "ZX Spectrum", ThemeCategory.RETRO_COMPUTING, zxSpectrumScheme),
        ThemeSpec(AppTheme.AMIGA, "Amiga Workbench", ThemeCategory.RETRO_COMPUTING, amigaScheme),
        ThemeSpec(AppTheme.APPLE_II, "Apple II", ThemeCategory.RETRO_COMPUTING, appleIIScheme),
    )
}
